# Generated by Django 5.1.5 on 2025-02-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=25)),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(upload_to='Shop/')),
            ],
        ),
    ]
